### ISSUE TITLE
xml.parsers.expat.ExpatError

### ISSUE THREAD

**Issue by Sylk1-9** [leighsmith/iTunes2Strawberry#1]
After running the following command

`python3 iTunes2Strawberry.py -s strawberry.db -i iTunes\ Library.xml -p`

I got the following error:

```
Traceback (most recent call last):
  File "iTunes2Strawberry.py", line 228, in <module>
    root = plistlib.load(libraryFile, fmt = plistlib.FMT_XML)
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 875, in load
    return p.parse(fp)
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/plistlib.py", line 177, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 951559, column 27
```

Have no idea if this comes from iTunes2Strawberry script, or from somewhere else. 

best regards

**Comment by leighsmith** [comment]
Hmm, it seems to come from the XML reading library (`plistlib`) attempting to read the `iTunes Library.xml` file, and is failing far down in that XML file at line 951559. I would suspect it's something to do with an extended character (beyond standard ASCII, UTF-8 or Unicode). You should be able to inspect that one line using the following command:

```
sed -n -e '951559p' iTunes\ Library.xml
```

If nothing looks untoward, try dumping the binary characters also?

```
sed -n -e '951559p' iTunes\ Library.xml | hexdump -C
```

**Comment by Sylk1-9** [comment]
Thanks, that solved the problem!

Indeed, by following your advice, the `sed` command return a track ID identifier, which can then be used to find the track information in the Library.xml file (just open it with a compatible text/code editor).

In my case, a few tracks had strange characters in the _genre_ tag.
